services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker1:
    image: confluentinc/cp-server:7.4.0
    hostname: broker1
    container_name: broker1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker1:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "broker1:29092", "--list"]
      interval: 5s
      timeout: 10s
      retries: 10

  topics-init:
    image: confluentinc/cp-kafka:7.4.0
    container_name: topics-init
    depends_on:
      broker1:
        condition: service_healthy
    restart: on-failure
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...';
        sleep 5;
        
        # Создаем топики
        kafka-topics --bootstrap-server broker1:29092 --create --if-not-exists --topic products_in --partitions 1 --replication-factor 1;
        kafka-topics --bootstrap-server broker1:29092 --create --if-not-exists --topic products --partitions 1 --replication-factor 1;

        kafka-topics --bootstrap-server broker1:29092 --create --if-not-exists --topic block --partitions 1 --replication-factor 1;
        kafka-topics --bootstrap-server broker1:29092 --create --if-not-exists --topic block-table --partitions 1 --replication-factor 1 --config cleanup.policy=compact;
        kafka-topics --bootstrap-server broker1:29092 --create --if-not-exists --topic user-actions --partitions 1 --replication-factor 1;

        echo 'Topics created successfully!';
        exit 0;
      "