services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_REQUIRE_CLIENT_AUTH_SCHEME: sasl
      ZOOKEEPER_AUTH_PROVIDER_1: "org.apache.zookeeper.server.auth.SASLAuthenticationProvider"
      ZOOKEEPER_SASL_ENABLED: true
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/zookeeper/zookeeper_server_jaas.conf"
    volumes:
      - ./secrets/zookeeper/zookeeper_server_jaas.conf:/etc/zookeeper/zookeeper_server_jaas.conf
    networks:
      pnet:


  broker1:
    image: confluentinc/cp-server:7.4.0
    hostname: b1.kafka.local
    container_name: broker1
    depends_on:
      - zookeeper
    ports:
      # - "9101:9101"
      - "9193:9193"
      - "9194:9194"

    env_file:
      - ./envs/kafka.common.env
      - ./envs/broker1.env # Подключаем общие переменные

    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "broker1:29092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - ./secrets/cluster-main_server_jaas.conf:/etc/kafka/jaas/kafka_server_jaas.conf
      - ./secrets/broker1/client.properties:/tmp/client.conf
      - ./secrets/broker1/creds:/etc/kafka/secrets
    networks:
      pnet:
        ipv4_address: 192.168.0.101

  broker2:
    image: confluentinc/cp-server:7.4.0
    hostname: b2.kafka.local
    container_name: broker2
    depends_on:
      - zookeeper
      - broker1
    ports:
      # - "9092:9092"
      # - "9101:9101"
      - "9293:9293"
      - "9294:9294"
      - 9912:9912
    env_file:
      - ./envs/kafka.common.env
      - ./envs/broker2.env # Подключаем общие переменные
      # environment:
      # KAFKA_JMX_OPTS: >-
      #   -Dcom.sun.management.jmxremote
      #   -Dcom.sun.management.jmxremote.port=9912
      #   -Dcom.sun.management.jmxremote.rmi.port=9912
      #   -Dcom.sun.management.jmxremote.authenticate=false
      #   -Dcom.sun.management.jmxremote.ssl=false
      #   -Djava.rmi.server.hostname=broker2=value
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "broker2:29092", "--list" ]
      interval: 2s
      timeout: 5s
      retries: 10
    volumes:
      - ./secrets/cluster-main_server_jaas.conf:/etc/kafka/jaas/kafka_server_jaas.conf
      - ./secrets/broker2/creds:/etc/kafka/secrets
    networks:
      pnet:
        ipv4_address: 192.168.0.102

  broker3:
    image: confluentinc/cp-server:7.4.0
    hostname: b3.kafka.local
    container_name: broker3
    depends_on:
      - zookeeper
      - broker1
    ports:
      # - "9092:9092"
      # - "9101:9101"
      - "9393:9393"
      - "9394:9394"
      - 9913:9913
    env_file:
      - ./envs/kafka.common.env
      - ./envs/broker3.env # Подключаем общие переменные
    # environment:
    #     KAFKA_JMX_OPTS: >-
    #       -Dcom.sun.management.jmxremote
    #       -Dcom.sun.management.jmxremote.port=9913
    #       -Dcom.sun.management.jmxremote.rmi.port=9913
    #       -Dcom.sun.management.jmxremote.authenticate=false
    #       -Dcom.sun.management.jmxremote.ssl=false
    #       -Djava.rmi.server.hostname=broker3=value
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "broker3:29092", "--list" ]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - ./secrets/cluster-main_server_jaas.conf:/etc/kafka/jaas/kafka_server_jaas.conf
      - ./secrets/broker3/creds:/etc/kafka/secrets
    networks:
      pnet:
        ipv4_address: 192.168.0.103

  topics-init:
    image: confluentinc/cp-kafka:7.4.0
    container_name: topics-init
    depends_on:
      broker1:
        condition: service_healthy
    restart: on-failure
    networks:
      pnet:
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...';
        sleep 15;
        
        # Создаем топики
        kafka-topics --bootstrap-server broker1:29092 --create --if-not-exists --topic products_in --partitions 1 --replication-factor 1;
        kafka-topics --bootstrap-server broker1:29092 --create --if-not-exists --topic products --partitions 1 --replication-factor 1;

        kafka-topics --bootstrap-server broker1:29092 --create --if-not-exists --topic block --partitions 1 --replication-factor 1;
        kafka-topics --bootstrap-server broker1:29092 --create --if-not-exists --topic block-table --partitions 1 --replication-factor 1 --config cleanup.policy=compact;
        kafka-topics --bootstrap-server broker1:29092 --create --if-not-exists --topic user-actions --partitions 3 --replication-factor 2;

        echo 'Topics created successfully!';
        exit 0;
      "

networks:
  pnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
