spark.master                     spark://spark-master:7077
spark.grpc.enabled               true
spark.grpc.server.port           15002
spark.grpc.server.bindAddress    0.0.0.0
spark.dynamicAllocation.enabled  false