KafkaServer {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="kafka-internal"
   password="H6tFPQDI9Wnu"
   user_kafka-internal="H6tFPQDI9Wnu"
   user_kafka-admin="bPuWs7hg9u6m"
   user_prometheus="4QVd7RCqiXKx"
   user_grafana="uHsBAUtpUnlR";
};
Client {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="zk-admin"
   password="Jf3VxN0uFCzV";
};