KafkaServer {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="kafka-internal"
   password="edTxpXFGT7vi"
   user_kafka-internal="edTxpXFGT7vi"
   user_kafka-admin="HyBWzClzPLAq"
   user_prometheus="4QVd7RCqiXKx"
   user_grafana="uHsBAUtpUnlR";
};
Client {
   org.apache.kafka.common.security.plain.PlainLoginModule required
   username="zk-admin"
   password="2qqBrjOBtyqe";
}; 